# This file will be AUTOMATICALLY GENERATED by the deploy script
# using nixos-generate-config on your actual hardware.
#
# This template is just to show what it will look like.
# DO NOT EDIT THIS FILE - it will be overwritten during deployment!

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Boot configuration for your AMD system
  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # CPU configuration
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  # High-DPI console (if needed)
  console.font =
    lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";

  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";

  # This will be filled in automatically with your actual hardware details
  # Things like:
  # - USB device IDs
  # - PCI device IDs
  # - Network interface names
  # - Sound card configuration
  # - etc.

  # The deploy script will generate this file specifically for YOUR hardware

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
